version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: villains
    volumes:
      - ./villains_dump.sql:/mnt/storage/dump.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  adminer:
    container_name: mysql-adminer
    image: adminer
    ports:
      - "8000:8080"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge